//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.18 at 07:12:12 PM CET 
//


package com.example.demo.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.demo.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.demo.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link GetAdvertisementRequest }
     * 
     */
    public GetAdvertisementRequest createGetAdvertisementRequest() {
        return new GetAdvertisementRequest();
    }

    /**
     * Create an instance of {@link GetAdvertisementResponse }
     * 
     */
    public GetAdvertisementResponse createGetAdvertisementResponse() {
        return new GetAdvertisementResponse();
    }

    /**
     * Create an instance of {@link Advertisement }
     * 
     */
    public Advertisement createAdvertisement() {
        return new Advertisement();
    }

    /**
     * Create an instance of {@link SetAdvertisementRequest }
     * 
     */
    public SetAdvertisementRequest createSetAdvertisementRequest() {
        return new SetAdvertisementRequest();
    }

    /**
     * Create an instance of {@link SetAdvertisementResponse }
     * 
     */
    public SetAdvertisementResponse createSetAdvertisementResponse() {
        return new SetAdvertisementResponse();
    }

    /**
     * Create an instance of {@link DeleteAdvertisementRequest }
     * 
     */
    public DeleteAdvertisementRequest createDeleteAdvertisementRequest() {
        return new DeleteAdvertisementRequest();
    }

    /**
     * Create an instance of {@link DeleteAdvertisementResponse }
     * 
     */
    public DeleteAdvertisementResponse createDeleteAdvertisementResponse() {
        return new DeleteAdvertisementResponse();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     * 
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link GetUserResponse }
     * 
     */
    public GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

    /**
     * Create an instance of {@link SetUserRequest }
     * 
     */
    public SetUserRequest createSetUserRequest() {
        return new SetUserRequest();
    }

    /**
     * Create an instance of {@link SetUserResponse }
     * 
     */
    public SetUserResponse createSetUserResponse() {
        return new SetUserResponse();
    }

    /**
     * Create an instance of {@link DeleteUserRequest }
     * 
     */
    public DeleteUserRequest createDeleteUserRequest() {
        return new DeleteUserRequest();
    }

    /**
     * Create an instance of {@link DeleteUserResponse }
     * 
     */
    public DeleteUserResponse createDeleteUserResponse() {
        return new DeleteUserResponse();
    }

    /**
     * Create an instance of {@link Rating }
     * 
     */
    public Rating createRating() {
        return new Rating();
    }

    /**
     * Create an instance of {@link User.CreatedAdvertisements }
     * 
     */
    public User.CreatedAdvertisements createUserCreatedAdvertisements() {
        return new User.CreatedAdvertisements();
    }

}
